version: "3.8"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn events.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db

  nginx:
    build: ./nginx
    volumes:
      - ./staticfiles:/home/app/code/staticfiles
    ports:
      - 8080:80
    depends_on:
      - web

  cronjobs:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["cron", "-f"]
    depends_on:
      - db
