# Generated by Django 3.2.4 on 2021-07-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210706_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='summary',
        ),
        migrations.AddField(
            model_name='article',
            name='original_url',
            field=models.URLField(null=True),
        ),
    ]
